import type { Metadata } from "next";
import { DM_Mono, Syne } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import CustomCursor from "@/components/custom-cursor";


const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const dmmono = DM_Mono({
  weight: '400',
  variable: "--font-dmmono",
  subsets: ["latin"],
})

const dirtyline = localFont({
  src: "../public/fonts/Dirtyline36Daysoftype2022-Reg.ttf",
  variable: "--font-dirtyline",
});


export const metadata: Metadata = {
  title: "TRIONN | Crafting Award-Winning Digital Journeys.",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.variable} ${dmmono.variable} ${dirtyline.variable} 
          font-sans antialiased selection:text-primary font-syne`}
      >
        <Navbar />
        {children}
        <CustomCursor />
      </body>
    </html>
  );
}
